diplom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path, include
from .views import *

app_name = 'main'

urlpatterns = [
    path('', product_list, name='list'),
    path('<int:id>/<slug:slug>/', product_detail.as_view(), name='main_detail'),
    path('login/', MyprojectLoginView.as_view(), name='login_page'),
    path('register/', RegisterUserView.as_view(), name='register_page'),
    path('logout/', MyProjectLogout.as_view(), name='logout_page'),
]

main/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.
class Post(models.Model):
    title = models.CharField("Название организации", max_length=200)
    description = models.TextField('О компании')
    adress = models.CharField("Адрес организации", max_length=200)
    director = models.CharField("Директор организации", max_length=200)
    phone_number = models.CharField("Телефон", max_length=200)
    image = models.ImageField(upload_to='photos/%Y/%m/%d')
    video = models.FileField(upload_to='filesInput/')
    slug = models.SlugField(max_length=200, db_index=True)

    class Meta:
        ordering = ('title',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
            return reverse('main:main_detail',
                           args=[self.id, self.slug])

class Comment(models.Model):
    author = models.ForeignKey(User, on_delete = models.CASCADE, verbose_name='Автор комментария', blank = True, null = True)
    post = models.ForeignKey(Post, on_delete = models.CASCADE, verbose_name='Статья', blank = True, null = True,related_name='comments_post')
    create_date = models.DateTimeField(default=timezone.now)
    text = models.TextField(verbose_name='Текст комментария')

main/forms.py
from django.forms import ModelForm
from .models import *
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
class AuthUserForm(AuthenticationForm, forms.ModelForm):
    class Meta:
        model = User
        fields = ('username','password')
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

class RegisterUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password')
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
        self.fields['text'].widget = forms.Textarea(attrs={'rows':5})

main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from django.views.generic.detail import DetailView
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import authenticate, login, logout
from .forms import *
from django.views.generic.edit import CreateView, FormMixin
from django.urls import reverse_lazy
from django.contrib.auth.models import User
# Create your views here.
def product_list(request):
    posts = Post.objects.all()
    return render(request,
                  'posts/list.html',
                  {'posts': posts})

class product_detail(FormMixin, DetailView):
    model = Post
    template_name = 'posts/detail.html'
    context_object_name = 'get_post'
    success_url = '/'
    form_class = CommentForm

    def get_success_url(self):
        return self.success_url

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = Post.objects.all()
        context['comments'] = Comment.objects.all().order_by('-create_date')
        return context

    def post(self,request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self,form):
        self.object = form.save(commit=False)
        self.object.post = self.get_object()
        self.object.author = self.request.user
        self.object.save()
        return super().form_valid(form)


class MyprojectLoginView(LoginView):
    template_name = 'posts/login.html'
    form_class = AuthUserForm
    success_url = reverse_lazy('main:list')
    def get_success_url(self):
        return self.success_url

class RegisterUserView(CreateView):
    model = User
    template_name = 'posts/register.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('main:list')
    success_msg = 'Пользователь успешно создан'
    def form_valid(self,form):
        form_valid = super().form_valid(form)
        username = form.cleaned_data["username"]
        password = form.cleaned_data["password"]
        aut_user = authenticate(username=username,password=password)
        login(self.request, aut_user)
        return form_valid

class MyProjectLogout(LogoutView):
    next_page = reverse_lazy('main:list')

main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>{% block title %}My shop{% endblock %}</title>
  <link href="{% static 'css/base.css' %}" rel="stylesheet">
</head>
<body>
  <div id="header">
    <a href="/" class="logo">My shop</a>
  </div>
  <div id="subheader">
    <div class="cart">
      <a href="{% url 'main:register_page' %}">Регистрация</a>
      <a href="{% url 'main:login_page' %}">Вход</a>
      <a href="{% url 'main:logout_page' %}">Выход</a>
      {% if user.is_authenticated %}
          Добро пожаловать, {{ user.username }}. Вы же уже авторизорваны.
      {% endif %}
    </div>
  </div>
  <div id="content">
    {% block content %}
    {% endblock %}
  </div>
</body>
</html>

main/templates/posts/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  {{ post.title }}
{% endblock %}

<script type="text/javascript">
    var video = document.getElementById('vidId');
        // or video = $('.video-selector')[0];
        video.pause();
        video.currentTime = 0;
        video.load();
</script>

{% block content %}
{% for post in posts %}
  <div class="product-detail">
    <img src="{{ post.image.url }}">
    <h1>{{ post.title }}</h1>
    <p>{{ post.description }}</p>
    <p>
      <video width="400" height="300" controls="controls">
         <source src="{{ post.video.url }}" type='video/mp4'>
      </video>
    </p>
    <p class='company'>{{ post.adress }}</p>
    <p class='company'>{{ post.director }}</p>
  </div>
    {% endfor %}
<div>
  <h2>Комментарии</h2>
  <hr>
          <p>Добавить комментарий</p>
          <div class="">
          <form action="" method="post">
              {% csrf_token %}
              {{ form.as_p }}
              <input type="submit" value="Добавить">
          </form>
          <hr>
  {% for comment in comments %}
      <p>{{ comment.author }}
      {{ comment.create_date }}</p>
      <p>{{ comment.text }}</p>
  {% endfor %}
</div>
{% endblock %}

main/templates/posts/list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <div id="main" class="product-list">
    {% for post in posts %}
        <p>{{ post.title }}</p>
        <p>{{ post.description|truncatewords:40|safe }}</p>
        <p><img src="{{ post.image.url }}" width="400" height="300"></p>
        <p class='company'>{{ post.adress }}</p>
        <p class='company'>{{ post.director }}</p>
        <a href="{{ post.get_absolute_url }}">Читать полностью</a>

    {% endfor %}
  </div>
{% endblock %}

main/templates/posts/login.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container">
      <h1>Вход на сайт</h1>
      {% if error %}
        <div style="color:red;">{{ error }}</div>
      {% endif %}
      <form method="post">
        {% csrf_token %}
        <p><input type="text" name="username" placeholder="Логин"></p><b>Имя пользователя</b>
        <p><b>Пароль</b><input type="password" name="password" placeholder="Пароль"></p>
        <p><a href="/"><input type="submit" value="Войти"></a></p>
      </form>
  </div>
{% endblock %}

main/templates/posts/register.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <h1>Регистрация</h1>
         <form method="post" >
             {% csrf_token %}
             <table>
                {{ form.as_table }}
                 <tr>
                    <td></td>
                    <td><input type="submit" name="submit" value="Register" /></td>
                </tr>
             </table>
         </form>
{% endblock %}